// Reference lists for the registration form's dropdowns.
//
// Nothing municipality-specific here: no authoritative source exists in
// this codebase for Barangay-level or City/Municipality-level data (checked
// both frontends and the backend — `postal_code`/`barangay`/`city` are all
// plain free-text columns, no reference table), and inventing one would be
// exactly the "plausible-looking invented figure" this codebase's other
// reference data (e.g. the fee schedule) deliberately refuses to ship. This
// file only holds the two lists that ARE small, stable, and truly universal
// enough to hardcode without risking being wrong: nationalities and PH
// provinces (PSGC). Barangay/City stay free text on the form.

/** "Filipino" first — the overwhelming majority of applicants, matching `nationality`'s existing default. "Other" last, paired with a free-text fallback in the UI rather than silently rejecting an uncommon answer. */
export const NATIONALITIES: readonly string[] = [
  'Filipino',
  'American',
  'Australian',
  'Bangladeshi',
  'Bruneian',
  'British',
  'Burmese',
  'Cambodian',
  'Canadian',
  'Chinese',
  'Emirati',
  'French',
  'German',
  'Indian',
  'Indonesian',
  'Italian',
  'Japanese',
  'Jordanian',
  'Kuwaiti',
  'Lao',
  'Malaysian',
  'Mongolian',
  'Nepalese',
  'New Zealander',
  'Pakistani',
  'Qatari',
  'Russian',
  'Saudi Arabian',
  'Singaporean',
  'South Korean',
  'Spanish',
  'Sri Lankan',
  'Taiwanese',
  'Thai',
  'Timorese',
  'Vietnamese',
  'Other',
];

/** The 82 PH provinces (PSGC) plus Metro Manila (NCR is region-level, not a province, but every PH address form offers it here since a Metro Manila resident has no province of their own to pick). "Sorsogon" is this LGU's own province — the default, matching `province`'s existing initial value. */
export const PH_PROVINCES: readonly string[] = [
  'Sorsogon',
  'Metro Manila (NCR)',
  'Abra',
  'Agusan del Norte',
  'Agusan del Sur',
  'Aklan',
  'Albay',
  'Antique',
  'Apayao',
  'Aurora',
  'Basilan',
  'Bataan',
  'Batanes',
  'Batangas',
  'Benguet',
  'Biliran',
  'Bohol',
  'Bukidnon',
  'Bulacan',
  'Cagayan',
  'Camarines Norte',
  'Camarines Sur',
  'Camiguin',
  'Capiz',
  'Catanduanes',
  'Cavite',
  'Cebu',
  'Cotabato',
  'Davao de Oro',
  'Davao del Norte',
  'Davao del Sur',
  'Davao Occidental',
  'Davao Oriental',
  'Dinagat Islands',
  'Eastern Samar',
  'Guimaras',
  'Ifugao',
  'Ilocos Norte',
  'Ilocos Sur',
  'Iloilo',
  'Isabela',
  'Kalinga',
  'La Union',
  'Laguna',
  'Lanao del Norte',
  'Lanao del Sur',
  'Leyte',
  'Maguindanao del Norte',
  'Maguindanao del Sur',
  'Marinduque',
  'Masbate',
  'Misamis Occidental',
  'Misamis Oriental',
  'Mountain Province',
  'Negros Occidental',
  'Negros Oriental',
  'Northern Samar',
  'Nueva Ecija',
  'Nueva Vizcaya',
  'Occidental Mindoro',
  'Oriental Mindoro',
  'Palawan',
  'Pampanga',
  'Pangasinan',
  'Quezon',
  'Quirino',
  'Rizal',
  'Romblon',
  'Samar',
  'Sarangani',
  'Siquijor',
  'South Cotabato',
  'Southern Leyte',
  'Sultan Kudarat',
  'Sulu',
  'Surigao del Norte',
  'Surigao del Sur',
  'Tarlac',
  'Tawi-Tawi',
  'Zambales',
  'Zamboanga del Norte',
  'Zamboanga del Sur',
  'Zamboanga Sibugay',
];
